### ISSUE TITLE
Checking post-conditions with returns

### ISSUE THREAD

**Issue by strat0sphere** [AndreaCensi/contracts#15]
Similar to an older issue regarding the "tried to redefine 'xxx' with a definition that looks different to me" error (https://github.com/AndreaCensi/contracts/issues/4 ), we can get the same problem when trying to redefine returns. Think of the case that we create two new contracts for different methods and we want in both cases to check their post condition, using the special name "returns".  For example in case in one method we want the return type to be bool and in another int we will get the following error: 
ValueError: Tried to redefine 'returns' with a definition that looks different to me. 
- old: SeparateContext(CheckType(bool)) 
- new: SeparateContext(CheckType(int))

Since checking what different function returns will always require "returns" redefinition wouldn't be better to add a check in main.py just before throwing the error and in case the identifier is "returns" just ignore it and continue? Is there any other way to do this postcondition checking other than using the "returns"? 

Also, any plans for supporting invariants? I checked this issue https://github.com/AndreaCensi/contracts/issues/10 already and I am wondering if you plan to develop this any time soon...

**Comment by AndreaCensi** [comment]
Closing this, I'm still not sure about the use case.
