### ISSUE TITLE
Unicode strings for contract names

### ISSUE THREAD

**Issue by brokenseal** [AndreaCensi/contracts#40]
Hi,
first of all, thanks for your awesome library!
Second, I added your library in a project of mine where I include unicode_literals (from __ future __) in all the modules, that is causing me some issues with your library because the contract decorator expects a lot of things but not a unicode object.

I was wondering if you could check on contracts/main.py:337 if the spec is an instance of basestring instead of str so that unicode will also match.

Thanks!

**Comment by AndreaCensi** [comment]
I fixed the checks that I could find so this might be partially fixed. The changes are in master and with the latest release 1.7.4. Let me know if I forgot some other check.

**Comment by brokenseal** [comment]
Yup, thank you :+1:
