### ISSUE TITLE
1.7.7 release on PyPI doesn't build for Python 3

### ISSUE THREAD

**Issue by felixonmars** [AndreaCensi/contracts#44]
`setup.py` fails with the following error, and the code doesn't seem to be here :/

```
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    version = get_version(filename='src/contracts/__init__.py')
  File "setup.py", line 24, in get_version
    with file(filename) as f:
NameError: name 'file' is not defined
```

**Comment by AndreaCensi** [comment]
oops - I'm traveling without Python3 access. Could you fix this and send a pull request? Thanks.

**Comment by felixonmars** [comment]
Thanks for the quick fix. I was trying to fix but didn't see the latest code on GitHub, so I have to open an issue only.

**Comment by AndreaCensi** [comment]
no problem - it's not really tested but Shippable says Python3 passes.
