### ISSUE TITLE
Exponential dimension relations in numpy arrays

### ISSUE THREAD

**Issue by StefanUlbrich** [AndreaCensi/contracts#54]
Hi Andrea,

I am working with numpy in high dimensional spaces for machine learning. I would like to use pycontracts to check dimension which have an exponential dependency e.g.:

arg1="array[N,M]", returns="array[N**M]"

Is there a way to check this? Is it alternatively possible to pass the dimension symbols (N,M,..) to contract defined by a function?

Best
Stefan

**Comment by AndreaCensi** [comment]
Fixed by Stefan himself.
